### ISSUE TITLE
Formatting of the project

### ISSUE THREAD

**Issue by dedifferentiator** [rmehri01/thock#10]
I'm currently trying to understand the code and I think it lacks a bit of formatting. I manually formatted one file, and if you like it and wouldn't mind, then I could format the others as well. 
But in general, there are the following options:

- Choose formatter (although I personally like none of them), optionally add it to CI (didn't see any, probably it will mean to write own github action) and format files on push/PR
- I'll reformat code and we'll have just to keep up with style
- Everything is fine, leave the things as they are

P.S. the project is amazing :)

**Comment by rmehri01** [comment]
Hi, thanks for the feedback! I have just been formatting my files manually with Ormolu since was the default one. While I don't like some things about it, I think that its nice to have a more opinionated formatter. Also there does seem to be a [github action for Ormolu](https://github.com/marketplace/actions/ormolu-action) so I could add that to CI as well to make sure it stays consistent!

**Comment by dedifferentiator** [comment]
Oh, ormolu... no wonder I thought there's no formatter at all haha, but that's okay! I'll just reformat the project as I like and before committing (if it will be) I'll revert formatting with ormolu. Yup, having that action would be great!

**Comment by rmehri01** [comment]
I just added the CI for this so I'm going to close this issue!
